### ISSUE TITLE
TODO for next release

### ISSUE THREAD

**Issue by esc** [Blosc/c-blosc#31]
I propose to get the next release out by mid January 2014. I am especially interested in integrating the support for alternative codecs we wroked on this summer. To that end I can currently remember the following storys:
- [x] Improve snappy support. We currently build against the snappy dynamic library and hard require this to be installed. Would be nice to support conditional compile as well as compiling snappy into the blosc binary. Snappy is built with CMake too (IIRC) so should be able to tie it in.
- [x] Debug remaining issues with Snappy on OSX. @FrancescAlted I recall you had some segfaults.
- [x] Support for `zlib`. Needs to be written and tested.
- [x] Test Windows/OSX Support for the above

The current development is at: http://git.io/xjHYkg lz4 support is ready, since we have added the sources to the blosc tree.

Anything else I have missed?
